### PR TITLE
substituted yoghurt with romme in cauliflower tacos; closes #3

### LINKED ISSUE #3: franzihe-issue
substitute Yogurt with Rømme

### PR DESCRIPTION
**Pull request by franzihe**

### CODE REVIEW

**Comment by devarajun** [comment]
It looks good. Well done.

**Comment by devarajun** [comment]
Could you mention the issue number.

**Comment by devarajun** [comment]
Ok, I see the issue number. I am merging your pull request

**Comment by franzihe** [comment]
Where would I put in the issue number so it closes it automatically?

**Pull request merged**
